#define CONFIG_FEATURE_ZSTD_SMALL 0
#define ENABLE_FEATURE_ZSTD_SMALL 1
#ifdef MAKE_SUID
# define IF_FEATURE_ZSTD_SMALL(...) __VA_ARGS__ "CONFIG_FEATURE_ZSTD_SMALL"
#else
# define IF_FEATURE_ZSTD_SMALL(...) __VA_ARGS__
#endif
#define IF_NOT_FEATURE_ZSTD_SMALL(...)
